package com.baeldung.spring.data.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Fines")
public class Fines {

    private String fineId;
    private String memberId;
    private String borrowId;
    private Integer fineAmount;
    private Boolean paid;
    private String issueDate;

    public Fines() {
    }

    public Fines(String fineId, String issueDate, Boolean paid, Integer fineAmount, String borrowId, String memberId) {
        this.fineId = fineId;
        this.issueDate = issueDate;
        this.paid = paid;
        this.fineAmount = fineAmount;
        this.borrowId = borrowId;
        this.memberId = memberId;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getFineId() {
        return fineId;
    }

    public void setFineId(String fineId) {
        this.fineId = fineId;
    }

    @DynamoDBAttribute
    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    @DynamoDBAttribute
    public String getBorrowId() {
        return borrowId;
    }

    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId;
    }

    @DynamoDBAttribute
    public Integer getFineAmount() {
        return fineAmount;
    }

    public void setFineAmount(Integer fineAmount) {
        this.fineAmount = fineAmount;
    }

    @DynamoDBAttribute
    public Boolean getPaid() {
        return paid;
    }

    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    @DynamoDBAttribute
    public String getIssueDate() {
        return issueDate;
    }

    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }
}
